import type { PlanetEncyclopediaEntry } from '../../types';

export const PLANET_ENCYCLOPEDIA: PlanetEncyclopediaEntry[] = [
  {
    stageNumber: 1,
    name: '月',
    emoji: '🌙',
    trivia: 'つきは ちきゅうの まわりを まわっているよ',
    planetColor: 0xcccccc,
    companionShape: 'basic',
  },
  {
    stageNumber: 2,
    name: '水星',
    emoji: '⚫',
    trivia: 'すいせいは たいように いちばん ちかい わくせいだよ',
    planetColor: 0x888888,
    companionShape: 'basic',
  },
  {
    stageNumber: 3,
    name: '金星',
    emoji: '🟡',
    trivia: 'きんせいは いちばん あつい わくせいだよ',
    planetColor: 0xddaa44,
    companionShape: 'basic',
  },
  {
    stageNumber: 4,
    name: '火星',
    emoji: '🔴',
    trivia: 'かせいは あかい すなで おおわれているよ',
    planetColor: 0xcc4422,
    companionShape: 'horned',
  },
  {
    stageNumber: 5,
    name: '木星',
    emoji: '🟠',
    trivia: 'もくせいは ちきゅうの 1000こぶん おおきいよ！',
    planetColor: 0xdd8844,
    companionShape: 'basic',
  },
  {
    stageNumber: 6,
    name: '土星',
    emoji: '🪐',
    trivia: 'どせいの わっかは こおりで できているよ',
    planetColor: 0xddaa44,
    companionShape: 'ringed',
  },
  {
    stageNumber: 7,
    name: '天王星',
    emoji: '🔵',
    trivia: 'てんのうせいは よこに たおれて まわっているよ',
    planetColor: 0x66ccdd,
    companionShape: 'icy',
  },
  {
    stageNumber: 8,
    name: '海王星',
    emoji: '🫧',
    trivia: 'かいおうせいは いちばん かぜが つよい わくせいだよ',
    planetColor: 0x2244cc,
    companionShape: 'bubble',
  },
  {
    stageNumber: 9,
    name: '冥王星',
    emoji: '❄️',
    trivia: 'めいおうせいは とっても ちいさい ほしだよ',
    planetColor: 0xbbaaaa,
    companionShape: 'icy',
  },
  {
    stageNumber: 10,
    name: '太陽',
    emoji: '☀️',
    trivia: 'たいようは もえている おおきな ほしだよ',
    planetColor: 0xffcc00,
    companionShape: 'radiant',
  },
  {
    stageNumber: 11,
    name: '地球',
    emoji: '🌍',
    trivia: 'ちきゅうは いのちが ある たったひとつの ほしだよ',
    planetColor: 0x2266aa,
    companionShape: 'basic',
  },
];
