import type { StageSpecialEventConfig } from '../../types';

export const STAGE_SPECIAL_EVENT_CONFIGS: readonly StageSpecialEventConfig[] = [
  {
    stageNumber: 1,
    id: 'moon-rabbit',
    style: 'rabbit',
    startProgress: 0.22,
    duration: 3.2,
    message: 'つきの うさぎさんだ！',
    accentColor: 0xe6f7ff,
  },
  {
    stageNumber: 2,
    id: 'mercury-twinkle',
    style: 'twinkle',
    startProgress: 0.28,
    duration: 2.8,
    message: 'きらりん ほしみち！',
    accentColor: 0xcfd8ff,
  },
  {
    stageNumber: 3,
    id: 'venus-veil',
    style: 'veil',
    startProgress: 0.36,
    duration: 3,
    message: 'ピカピカ ベール！',
    accentColor: 0xffd778,
  },
  {
    stageNumber: 4,
    id: 'mars-dust',
    style: 'dust',
    startProgress: 0.3,
    duration: 3.2,
    message: 'あかい すなかぜだ！',
    accentColor: 0xff8b5c,
  },
  {
    stageNumber: 5,
    id: 'jupiter-halo',
    style: 'halo',
    startProgress: 0.45,
    duration: 3,
    message: 'おおきな うずが くるくる！',
    accentColor: 0xffc778,
  },
  {
    stageNumber: 6,
    id: 'saturn-ring',
    style: 'ring',
    startProgress: 0.42,
    duration: 3.2,
    message: 'リングを くぐったよ！',
    accentColor: 0xffde87,
  },
  {
    stageNumber: 7,
    id: 'uranus-aurora',
    style: 'aurora',
    startProgress: 0.5,
    duration: 3,
    message: 'ふわり オーロラ！',
    accentColor: 0x8ff6ff,
  },
  {
    stageNumber: 8,
    id: 'neptune-bubbles',
    style: 'bubble',
    startProgress: 0.34,
    duration: 3.4,
    message: 'あおい あわが ぷかぷか！',
    accentColor: 0x7ec9ff,
  },
  {
    stageNumber: 9,
    id: 'pluto-crystal',
    style: 'crystal',
    startProgress: 0.4,
    duration: 3.1,
    message: 'こおりの きらきら！',
    accentColor: 0xe9f6ff,
  },
  {
    stageNumber: 10,
    id: 'sun-flare',
    style: 'flare',
    startProgress: 0.52,
    duration: 2.7,
    message: 'たいよう パワー ぴかーん！',
    accentColor: 0xffd54d,
  },
  {
    stageNumber: 11,
    id: 'station-halo',
    style: 'halo',
    startProgress: 0.46,
    duration: 3.1,
    message: 'ステーションが きらり！',
    accentColor: 0xb7d8ff,
  },
  {
    stageNumber: 12,
    id: 'earth-homecoming',
    style: 'homecoming',
    startProgress: 0.48,
    duration: 3.3,
    message: 'おかえりの ひかりだよ！',
    accentColor: 0x86d7ff,
  },
] as const;

export function getStageSpecialEventConfig(stageNumber: number): StageSpecialEventConfig | null {
  return STAGE_SPECIAL_EVENT_CONFIGS.find((config) => config.stageNumber === stageNumber) ?? null;
}
